import json
import os
from typing import Dict, Any, Optional

def send_slack_alert(message: Dict[str, Any], webhook_url: str = None) -> Dict[str, Any]:
    """
    Send alert to Slack
    """
    if webhook_url is None:
        webhook_url = os.getenv("SLACK_WEBHOOK_URL", "demo-webhook")
    
    # Extract key information
    what_happened = message.get("what_happened", "No summary available")
    urgency = message.get("urgency", "medium")
    sentiment = message.get("sentiment", "neutral")
    
    # Create Slack message
    slack_message = {
        "text": f"🚨 Forum Thread Alert - Urgency: {urgency.upper()}",
        "blocks": [
            {
                "type": "header",
                "text": {
                    "type": "plain_text",
                    "text": f"📋 Thread Summary Alert"
                }
            },
            {
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*What happened:*\n{what_happened}"
                }
            },
            {
                "type": "section",
                "fields": [
                    {
                        "type": "mrkdwn",
                        "text": f"*Urgency:*\n{urgency}"
                    },
                    {
                        "type": "mrkdwn", 
                        "text": f"*Sentiment:*\n{sentiment}"
                    }
                ]
            },
            {
                "type": "divider"
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "mrkdwn",
                        "text": "Generated by Forum Insights TL;DR Bot"
                    }
                ]
            }
        ]
    }
    
    print(f"[INFO] Slack alert prepared: {json.dumps(slack_message, indent=2)}")
    
    # In production, you would actually send to Slack
    # response = requests.post(webhook_url, json=slack_message)
    
    return {
        "status": "sent",
        "platform": "slack",
        "message_preview": what_happened[:100],
        "urgency": urgency,
        "mock": webhook_url == "demo-webhook"
    }

def send_email_alert(message: Dict[str, Any], recipient: str = None) -> Dict[str, Any]:
    """
    Send alert via email
    """
    if recipient is None:
        recipient = os.getenv("ALERT_EMAIL", "admin@example.com")
    
    subject = f"Forum Alert: {message.get('urgency', 'Medium')} Priority Thread"
    
    # Create email content
    email_content = f"""
    Forum Insights Alert
    ===================
    
    Thread Summary:
    {message.get('what_happened', 'No summary')}
    
    Key Details:
    - Root Causes: {', '.join(message.get('root_cause', ['Not specified']))}
    - Recommended Actions: {', '.join(message.get('remediation', ['Monitor thread']))}
    - Sentiment: {message.get('sentiment', 'Unknown')}
    - Urgency: {message.get('urgency', 'Medium')}
    
    ---
    This is an automated alert from Forum Insights TL;DR Bot.
    """
    
    print(f"[INFO] Email alert prepared for {recipient}")
    
    return {
        "status": "sent",
        "platform": "email",
        "recipient": recipient,
        "subject": subject,
        "content_preview": email_content[:200]
    }

def dispatch(message: Dict[str, Any], method: str = "slack", **kwargs) -> Dict[str, Any]:
    """
    Dispatch notification via specified method
    """
    method = method.lower()
    
    if method == "slack":
        return send_slack_alert(message, kwargs.get("webhook_url"))
    elif method == "email":
        return send_email_alert(message, kwargs.get("recipient"))
    elif method == "both":
        slack_result = send_slack_alert(message, kwargs.get("webhook_url"))
        email_result = send_email_alert(message, kwargs.get("recipient"))
        return {
            "status": "sent_multiple",
            "slack": slack_result,
            "email": email_result
        }
    else:
        return {
            "status": "error",
            "message": f"Unknown dispatch method: {method}",
            "supported_methods": ["slack", "email", "both"]
        }

if __name__ == "__main__":
    # Test dispatch
    test_message = {
        "what_happened": "Users reporting critical authentication failures",
        "root_cause": ["API key validation bug", "Rate limiting misconfiguration"],
        "remediation": ["Rollback authentication service", "Emergency patch deployment"],
        "sentiment": "negative",
        "urgency": "high"
    }
    
    result = dispatch(test_message, "slack")
    print(f"Dispatch result: {result}")
